import DefaultLayout from '@/components/layouts/default/DefaultLayout';
import Head from 'next/head';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold">
        Nextjs Typescript +{' '}
        <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
          TailwindCSS
        </span>{' '}
        Template
      </h1>
    </>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <DefaultLayout>{page}</DefaultLayout>;
};
